### ISSUE TITLE
transition to `sf` and `terra`

### ISSUE THREAD

**Issue by simoncarrignon** [josephlewis/leastcostpath#7]
Title is pretty much self explanatory. The packages `sp` and `raster`, actually used by `leastcostpath`, are going to be replaced soon by `sf` and `terra`, while `rgdal` and `rgeos`, also used by `leastcostpath` "will be retired by the end of 2023"
![image](https://user-images.githubusercontent.com/4749455/159348960-67be75c1-686d-49ea-b0ee-55dd5c68ed3c.png)

It's then probably time to start this transition for `leastcostpath`!

One issue, and the reason why `leastcostpath` still relies on `sp` and `raster`, is its dependancy to `gdistance`, which still uses those packages. Thought this has already been mentioned two years ago in: AgrDataSci/gdistance#3, it's not clear if the switch will be done anytime soon. A first, temporary easy fix would be to cast all object into `raster` and `Spatial` before calling for `gdistances` functions.

**Comment by josephlewis** [comment]
This is currently in progress. See dev branch

**Comment by josephlewis** [comment]
leastcostpath version 2.0.0 and onwards will use sf and terra. The dependency on gdistance has been removed
